# Generated by Django 5.1.2 on 2025-06-23 21:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgresoSemanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horasSemanales', models.PositiveIntegerField(default=0)),
                ('topicosCubiertos', models.PositiveIntegerField(default=0)),
                ('totalTopicos', models.PositiveIntegerField(default=0)),
                ('subjectProgress', models.JSONField(default=dict, help_text="Formato: {'matematicas': 50, 'lenguaje': 70, 'ciencias': 40, 'historia': 90}")),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
