# Generated by Django 5.1.2 on 2025-06-23 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='progresosemanal',
            name='avanceObjetivo',
            field=models.JSONField(default=dict, help_text="Ej: {'matematicas': 0.8, 'lenguaje': 0.6}"),
        ),
        migrations.AddField(
            model_name='progresosemanal',
            name='erroresComunes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='progresosemanal',
            name='notasObjetivos',
            field=models.JSONField(default=dict, help_text="Formato: {'matematicas': 650, 'lenguaje': 720, ...}"),
        ),
        migrations.AddField(
            model_name='progresosemanal',
            name='notasSimulacros',
            field=models.JSONField(default=dict, help_text="Formato: {'matematicas': 650, 'lenguaje': 720, ...}"),
        ),
        migrations.AddField(
            model_name='progresosemanal',
            name='porcentajeObjetivosCumplidos',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='progresosemanal',
            name='puntuacionAutodiagnostico',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='progresosemanal',
            name='sesionesEstudio',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='progresosemanal',
            name='tiempoPromedioGeneral',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='progresosemanal',
            name='tiempoPromedioPorSesion',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='progresosemanal',
            name='ultimaFechaActualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
